In [1]:
# Importar librería para la conexión con MySQL
# -----------------------------------------------------------------------
import mysql.connector
from mysql.connector import errorcode


# Importar librerías para manipulación y análisis de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np


# importamos las librerías que necesitaremos
# Importar librería para trabajar con archivos JSON
# -----------------------------------------------------------------------
import json
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

## Insertamos datos tabla Oscars

In [2]:
#leemos el csv

df_oscars = pd.read_csv("CSV_JSON_F4/lista_tuplas_fase4.csv", index_col = 0)

#Hacemos una lista con el nombre de las columnas actuales del data frame
columnas_actuales = df_oscars.columns.tolist()

#Definimos el nombre de las columnas
nuevos_nombres = ['FechaCeremonia', 'MejorPelicula', 'MejorDirector', 'MejorActor', 'MejorActriz']

#Cambiamos el nombre de las columnas por la lista que hemos creado
df_oscars.columns = nuevos_nombres

In [3]:

# Conectar a la base de datos
cnx = mysql.connector.connect(user='root', password='MySQLPassword2023!',
                              host='127.0.0.1', database='moviemakers')
mycursor = cnx.cursor()



#Iteramos por cada uno de los elementos

for index, row in df_oscars.iterrows():
    sql = """
        INSERT INTO Oscars (FechaCeremonia, MejorPelicula, MejorDirector, MejorActor, MejorActriz) 
        VALUES ( %s, %s, %s, %s, %s)
    """
    values = (row['FechaCeremonia'], row['MejorPelicula'], row['MejorDirector'], row['MejorActor'], row['MejorActriz'])
    
    try:
        mycursor.execute(sql, values)
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        print("Error Code:", err.errno)
        print("SQLSTATE", err.sqlstate)
        print("Message", err.msg)

# Confirmar la inserción
cnx.commit()

print(f'Se han insertado los datos correctamente')
# Cerrar conexión
mycursor.close()
cnx.close()

Se han insertado los datos correctamente

## Insertamos datos tabla películas

In [4]:
#leemos el csv

df_peliculas = pd.read_csv("CSV_JSON_F1/resultado_tuplas_total.csv")  #cambiar el nombre del archivo

#Hacemos una lista con el nombre de las columnas actuales del data frame
columnas_actuales = df_peliculas.columns.tolist()

#Definimos el nombre de las columnas
nuevos_nombres = ['Tipo', 'Nombre', 'AnioEstreno', 'MesEstreno', 'IdPelicula']

#Cambiamos el nombre de las columnas por la lista que hemos creado
df_peliculas.columns = nuevos_nombres



#Combertimos en INT las columnas AnioEstreno y MesEstreno porque daba error de NAN Además convertimos el ano y mes en INT

df_peliculas['AnioEstreno'] = df_peliculas['AnioEstreno'].fillna(0).astype(int)
df_peliculas['MesEstreno'] = df_peliculas['MesEstreno'].fillna(0).astype(int)

#Eliminamos duplicados 
df_peliculas = df_peliculas.drop_duplicates()

In [5]:

# Conectar a la base de datos
cnx = mysql.connector.connect(user='root', password='MySQLPassword2023!',
                              host='127.0.0.1', database='moviemakers')
mycursor = cnx.cursor()



#Iteramos por cada uno de los elementos

for index, row in df_peliculas.iterrows():           
    sql = """
        INSERT INTO Peliculas (Tipo, Nombre, AnioEstreno, MesEstreno, IdPelicula) 
        VALUES ( %s, %s, %s, %s, %s)
    """
    values = (row['Tipo'], row['Nombre'], row['AnioEstreno'], row['MesEstreno'], row['IdPelicula'])
    
    try:
        mycursor.execute(sql, values)
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        print("Error Code:", err.errno)
        print("SQLSTATE", err.sqlstate)
        print("Message", err.msg)

# Confirmar la inserción
cnx.commit()

print(f'Se han insertado los datos correctamente')
# Cerrar conexión
mycursor.close()
cnx.close()

Error: 1062 (23000): Duplicate entry 'tt29402528' for key 'peliculas.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'tt29402528' for key 'peliculas.PRIMARY'
Error: 1062 (23000): Duplicate entry 'tt29538571' for key 'peliculas.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'tt29538571' for key 'peliculas.PRIMARY'
Se han insertado los datos correctamente

## Insertamos datos tabla caracteristicas películas

In [6]:
#leemos el csv

df_caracteristicas_peliculas = pd.read_csv("CSV_JSON_F2/archivo_final_actualizado.csv")  #cambiar el nombre del archivo

#Hacemos una lista con el nombre de las columnas actuales del data frame
columnas_actuales = df_caracteristicas_peliculas.columns.tolist()

#Definimos el nombre de las columnas
nuevos_nombres = ['PuntuacionIMDB', 'PuntuacionTomatoes', 'Directores', 'Guionistas', 'Argumento', 'Genero', 'DuracionMinutos', 'Nombre', 'idPelicula']

#Cambiamos el nombre de las columnas por la lista que hemos creado
df_caracteristicas_peliculas.columns = nuevos_nombres

#Eliminamos duplicados 
df_caracteristicas_peliculas = df_caracteristicas_peliculas.drop_duplicates()

# cambiamos en el dataframe la , por . lo convertimos en float y quitomos los errorer Nan

df_caracteristicas_peliculas['PuntuacionIMDB'] = df_caracteristicas_peliculas['PuntuacionIMDB'].str.replace(',', '.')
df_caracteristicas_peliculas['PuntuacionIMDB'] = df_caracteristicas_peliculas['PuntuacionIMDB'].fillna('Null').astype(float)
df_caracteristicas_peliculas['PuntuacionTomatoes'] = df_caracteristicas_peliculas['PuntuacionTomatoes'].fillna('Null').astype(float)
df_caracteristicas_peliculas['Directores'] = df_caracteristicas_peliculas['Directores'].fillna('Null')
df_caracteristicas_peliculas['Guionistas'] = df_caracteristicas_peliculas['Guionistas'].fillna('Null')
df_caracteristicas_peliculas['Argumento'] = df_caracteristicas_peliculas['Argumento'].fillna('Null')
df_caracteristicas_peliculas['Genero'] = df_caracteristicas_peliculas['Genero'].fillna('Null')
df_caracteristicas_peliculas['DuracionMinutos'] = df_caracteristicas_peliculas['DuracionMinutos'].fillna('Null')
df_caracteristicas_peliculas['Nombre'] = df_caracteristicas_peliculas['Nombre'].fillna('Null')

In [7]:
# Conectar a la base de datos
cnx = mysql.connector.connect(user='root', password='MySQLPassword2023!',
                              host='127.0.0.1', database='moviemakers')
mycursor = cnx.cursor()



#Iteramos por cada uno de los elementos

for index, row in df_caracteristicas_peliculas.iterrows():           
    sql = """
        INSERT INTO Peliculas_caracteristicas (PuntuacionIMDB, PuntuacionTomatoes, Directores, Guionistas, Argumento, Genero, DuracionMinutos, Nombre, idPelicula) 
        VALUES ( %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """
    values = (row['PuntuacionIMDB'], row['PuntuacionTomatoes'], row['Directores'], row['Guionistas'], row['Argumento'], row['Genero'], row['DuracionMinutos'] , row['Nombre'], row['idPelicula'])
    
    try:
        mycursor.execute(sql, values)
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        print("Error Code:", err.errno)
        print("SQLSTATE", err.sqlstate)
        print("Message", err.msg)

# Confirmar la inserción
cnx.commit()

print(f'Se han insertado los datos correctamente')
# Cerrar conexión
mycursor.close()
cnx.close()

Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Error: 1048 (23000): Column 'IdPelicula' cannot be null
Error Code: 1048
SQLSTATE 23000
Message Column 'IdPelicula' cannot be null
Se han insertado los datos correctamente

## Insertamos datos tabla Actores

In [14]:
#leemos el csv

df_actores = pd.read_csv("Completos_Final.csv")  #cambiar el nombre del archivo

In [18]:
df_actores.drop(columns='Unnamed: 0', inplace=True)

In [19]:
df_actores

,0,1,2,3,4
0,James Purefoy,1964,"['Roma', '2005–2007 • 22 episodios', 'Hap Coll...","['Reparto', 'Producción']",['Academy of Science Fiction Fantasy & Horror ...
1,David Arquette,1971,"['Scream 3', 'Nunca me han besado', 'Scream 2'...","['Producción', 'Reparto', 'Dirección']","['Blockbuster Entertainment Awards Gan', 'Brec..."
2,Amy Smart,1976,['Starship Troopers (Las brigadas del espacio)...,"['Reparto', 'Banda sonora']","['MTV Movie + TV Awards Gan', 'Teen Choice Awa..."
3,Frances Fisher,1952,"['Titanic', 'Sin perdón', 'Amor de calendario'...","['Reparto', 'Cámara y electricidad']","['Screen Actors Guild Awards Nom', 'Chlotrudis..."
4,Mariel Hemingway,1961,"['Manhattan', 'Superman IV: En busca de la paz...","['Reparto', 'Producción', 'Equipo ejecutivo']","['Academy Awards USA Nom', 'BAFTA Awards Nom',..."
...,...,...,...,...,...
1048,Vanessa Hudgens,1988,"['High School Musical 3: Fin de curso', 'Sprin...","['Reparto', 'Producción', 'Banda sonora']","['Heartland International Film Festival Gan', ..."
1049,Christopher Abbott,1986,"['Llega de noche', 'Possessor Uncut', 'Pobres ...","['Reparto', 'Producción', 'Banda sonora']","['Critics Choice Awards Nom', 'Chicago Film Cr..."
1050,Keith David,1956,"['Tiana y el sapo', 'Están vivos', 'Armageddon...","['Reparto', 'Producción', 'Composición']","['Daytime Emmy Awards Nom', 'Primetime Emmy Aw..."
1051,Arturo Castro,1985,"['Broad City', '2014–2019 • 25 episodios', '20...","['Reparto', 'Guion', 'Producción']","['Imagen Foundation Awards Nom', 'Orlando Film..."
1052,Jaden Smith,1998,"['The Karate Kid', 'After Earth', 'En busca de...","['Reparto', 'Composición', 'Dirección']",['Academy of Science Fiction Fantasy & Horror ...

In [20]:
#Hacemos una lista con el nombre de las columnas actuales del data frame
columnas_actuales = df_actores.columns.tolist()

#Definimos el nombre de las columnas
nuevos_nombres = ['Nombre', 'AnioNacimiento', 'ConocidoPor', 'ActividadActual', 'Premios']

#Cambiamos el nombre de las columnas por la lista que hemos creado
df_actores.columns = nuevos_nombres

#Eliminamos duplicados 
df_actores = df_actores.drop_duplicates()

In [22]:
df_actores

,Nombre,AnioNacimiento,ConocidoPor,ActividadActual,Premios
0,James Purefoy,1964,"['Roma', '2005–2007 • 22 episodios', 'Hap Coll...","['Reparto', 'Producción']",['Academy of Science Fiction Fantasy & Horror ...
1,David Arquette,1971,"['Scream 3', 'Nunca me han besado', 'Scream 2'...","['Producción', 'Reparto', 'Dirección']","['Blockbuster Entertainment Awards Gan', 'Brec..."
2,Amy Smart,1976,['Starship Troopers (Las brigadas del espacio)...,"['Reparto', 'Banda sonora']","['MTV Movie + TV Awards Gan', 'Teen Choice Awa..."
3,Frances Fisher,1952,"['Titanic', 'Sin perdón', 'Amor de calendario'...","['Reparto', 'Cámara y electricidad']","['Screen Actors Guild Awards Nom', 'Chlotrudis..."
4,Mariel Hemingway,1961,"['Manhattan', 'Superman IV: En busca de la paz...","['Reparto', 'Producción', 'Equipo ejecutivo']","['Academy Awards USA Nom', 'BAFTA Awards Nom',..."
...,...,...,...,...,...
1048,Vanessa Hudgens,1988,"['High School Musical 3: Fin de curso', 'Sprin...","['Reparto', 'Producción', 'Banda sonora']","['Heartland International Film Festival Gan', ..."
1049,Christopher Abbott,1986,"['Llega de noche', 'Possessor Uncut', 'Pobres ...","['Reparto', 'Producción', 'Banda sonora']","['Critics Choice Awards Nom', 'Chicago Film Cr..."
1050,Keith David,1956,"['Tiana y el sapo', 'Están vivos', 'Armageddon...","['Reparto', 'Producción', 'Composición']","['Daytime Emmy Awards Nom', 'Primetime Emmy Aw..."
1051,Arturo Castro,1985,"['Broad City', '2014–2019 • 25 episodios', '20...","['Reparto', 'Guion', 'Producción']","['Imagen Foundation Awards Nom', 'Orlando Film..."
1052,Jaden Smith,1998,"['The Karate Kid', 'After Earth', 'En busca de...","['Reparto', 'Composición', 'Dirección']",['Academy of Science Fiction Fantasy & Horror ...

In [23]:
# Conectar a la base de datos
cnx = mysql.connector.connect(user='root', password='MySQLPassword2023!',
                              host='127.0.0.1', database='moviemakers')
mycursor = cnx.cursor()



#Iteramos por cada uno de los elementos

for index, row in df_actores.iterrows():           
    sql = """
        INSERT INTO actores (Nombre, AnioNacimiento, ConocidoPor, ActividadActual, Premios) 
        VALUES ( %s, %s, %s, %s, %s)
    """
    values = (row['Nombre'], row['AnioNacimiento'], row['ConocidoPor'], row['ActividadActual'], row['Premios'])
    
    try:
        mycursor.execute(sql, values)
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        print("Error Code:", err.errno)
        print("SQLSTATE", err.sqlstate)
        print("Message", err.msg)

# Confirmar la inserción
cnx.commit()

print(f'Se han insertado los datos correctamente')
# Cerrar conexión
mycursor.close()
cnx.close()

Error: 1062 (23000): Duplicate entry 'Owen Wilson' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Owen Wilson' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Kevin Bacon' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Kevin Bacon' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'James Purefoy' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'James Purefoy' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Simon Baker' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Simon Baker' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Sally Kirkland' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Sally Kirkland' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Giancarlo Esposito' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Giancarlo Esposito' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Hayley Atwell' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Hayley Atwell' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Anthony Mackie' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Anthony Mackie' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Kevin Durand' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Kevin Durand' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Rachel Nichols' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Rachel Nichols' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Mark Ruffalo' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Mark Ruffalo' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'John Gallagher Jr.' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'John Gallagher Jr.' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Oscar Isaac' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Oscar Isaac' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Ron Perlman' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Ron Perlman' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Ben Kingsley' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Ben Kingsley' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Sam Rockwell' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Sam Rockwell' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Mickey Rourke' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Mickey Rourke' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Samuel L. Jackson' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Samuel L. Jackson' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Clark Gregg' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Clark Gregg' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Angelina Jolie' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Angelina Jolie' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Paul Bettany' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Paul Bettany' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Karl Urban' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Karl Urban' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Vladimir Mashkov' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Vladimir Mashkov' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Carice van Houten' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Carice van Houten' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Adrien Brody' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Adrien Brody' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Jena Malone' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Jena Malone' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Nicole Kidman' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Nicole Kidman' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Kerry Washington' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Kerry Washington' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Cam Gigandet' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Cam Gigandet' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Tom Holland' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Tom Holland' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Alfred Molina' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Alfred Molina' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Lara Dutta' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Lara Dutta' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Emily Blunt' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Emily Blunt' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Paul Giamatti' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Paul Giamatti' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Stanley Tucci' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Stanley Tucci' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Liza Lapira' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Liza Lapira' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Richard Jenkins' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Richard Jenkins' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Megan Fox' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Megan Fox' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Chris Hemsworth' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Chris Hemsworth' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Natalie Portman' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Natalie Portman' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Christian Bale' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Christian Bale' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Idris Elba' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Idris Elba' for key 'actores.PRIMARY'
Error: 1062 (23000): Duplicate entry 'Vanessa Hudgens' for key 'actores.PRIMARY'
Error Code: 1062
SQLSTATE 23000
Message Duplicate entry 'Vanessa Hudgens' for key 'actores.PRIMARY'
Se han insertado los datos correctamente

## Insertamos datos tabla Actuaciones

In [26]:
#leemos el csv

df_actuaciones = pd.read_csv("Tabla_intermedia_Final.csv")  #cambiar el nombre del archivo

In [28]:
df_actuaciones.drop(columns='Unnamed: 0', inplace=True)

In [29]:
df_actuaciones

               0                   1
0     tt10429158       Aamu Milonoff
1     tt10429158         Linnea Skog
2     tt10429158      Elina Knihtilä
3     tt10429158        Jani Volanen
4     tt10429158      Minna Haapkylä
...          ...                 ...
1447  tt23461428      K.S. Ravikumar
1448  tt23461428  Dhanya Balakrishna
1449  tt23461428           Kapil Dev
1450  tt23461428             Nirosha
1451  tt23461428      Thambi Ramaiah

[1452 rows x 2 columns]

In [30]:
#Hacemos una lista con el nombre de las columnas actuales del data frame
columnas_actuales = df_actuaciones.columns.tolist()

#Definimos el nombre de las columnas
nuevos_nombres = ['IdPelicula', 'NombreActor']

#Cambiamos el nombre de las columnas por la lista que hemos creado
df_actuaciones.columns = nuevos_nombres

#Eliminamos duplicados 
df_actuaciones = df_actuaciones.drop_duplicates()

In [31]:
# Conectar a la base de datos
cnx = mysql.connector.connect(user='root', password='MySQLPassword2023!',
                              host='127.0.0.1', database='moviemakers')
mycursor = cnx.cursor()



#Iteramos por cada uno de los elementos

for index, row in df_actuaciones.iterrows():           
    sql = """
        INSERT INTO actuaciones (IdPelicula, NombreActor) 
        VALUES ( %s, %s)
    """
    values = (row['IdPelicula'], row['NombreActor'])
    
    try:
        mycursor.execute(sql, values)
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        print("Error Code:", err.errno)
        print("SQLSTATE", err.sqlstate)
        print("Message", err.msg)

# Confirmar la inserción
cnx.commit()

print(f'Se han insertado los datos correctamente')
# Cerrar conexión
mycursor.close()
cnx.close()

Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000
Message Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`moviemakers`.`actuaciones`, CONSTRAINT `actuaciones_ibfk_2` FOREIGN KEY (`NombreActor`) REFERENCES `actores` (`Nombre`))
Error Code: 1452
SQLSTATE 23000